### PR TITLE
Support UDP proxy to communicate with a real server.

### PR DESCRIPTION
**Pull request by winlinvip**
I use pion to test my open-source WebRTC server [SRS](https://github.com/ossrs/srs/blob/develop/.circleci/config.yml#L52), I write a tool [srs-bench](https://github.com/ossrs/srs-bench/tree/feature/rtc#srs-bench) to do benchmark and regression test.

Pion is useful and powerful, especially the interceptor and vnet, to enable us to do network hijack and simulate. Thanks very much!

I file this PR to support a UDP proxy to vnet, so that we can test a real server. It looks like this:

```
                           ..............................................
                           :         Virtual Network (vnet)             :
                           :                                            :
   +-------+ *         1 +----+         +--------+                      :
   | :App  |------------>|:Net|--o<-----|:Router |          .............................
   +-------+             +----+         |        |          :        UDPProxy           :
                           :            |        |       +----+     +---------+     +---------+     +--------+
                           :            |        |--->o--|:Net|-->o-| vnet.   |-->o-|  net.   |--->-| :Real  |
                           :            |        |       +----+     | UDPConn |     | UDPConn |     | Server |
                           :            |        |          :       +---------+     +---------+     +--------+
                           :            |        |          ............................:
                           :            +--------+                       :
                           ...............................................
```

Without this, the server must use vnet too, it limits the use of pion.

If the UDP proxy is supported, the big picture of vnet looks like this:

```
                          ......................................
                          :         Virtual Network (vnet)     :
                          :                                    :
  +-------+ *         1 +----+         +--------+              :
  | :App  |------------>|:Net|--o<-----|:Router |          .............................
  +-------+             +----+         |        |          :        UDPProxy           :
  +-----------+ *     1 +----+         |        |       +----+     +---------+     +---------+     +--------+
  |:STUNServer|-------->|:Net|--o<-----|        |--->o--|:Net|-->o-| vnet.   |-->o-|  net.   |--->-| :Real  |
  +-----------+         +----+         |        |       +----+     | UDPConn |     | UDPConn |     | Server |
  +-----------+ *     1 +----+         |        |          :       +---------+     +---------+     +--------+
  |:TURNServer|-------->|:Net|--o<-----|        |          ............................:
  +-----------+         +----+ [1]     |        |              :
                          :          1 |        | 1  <<has>>   :
                          :      +---<>|        |<>----+ [2]   :
                          :      |     +--------+      |       :
                        To form  |      *|             v 0..1  :
                  a subnet tree  |       o [3]      +-----+    :
                          :      |       ^          |:NAT |    :
                          :      |       |          +-----+    :
                          :      +-------+                     :
                          ......................................
```

I add some utests and examples to the UDP proxy, please let me know what should I do next?

Best regard.

### CODE REVIEW

**Comment by Sean-Der** [comment]
Wow this is really amazing work! I would love to get this merged @winlinvip 

I also think it will be very easy. Since this is new code and a utility I am all for it. I will review first thing in the morning :)

After we get this merged would love to post on Twitter about this! More people should know about this. SRS is such a fantastic project, it is an honor that Pion can be involved.

**Comment by winlinvip** [comment]
@Sean-Der Thanks very much!

**Comment by Sean-Der** [comment]
Merged with c0ffc291b9559a02411617f97e362b0bf0ff7d6e

Thanks for doing this @winlinvip I just refactored things to be real tests/examples

**Comment by winlinvip** [comment]
@Sean-Der Got it. I will file more PullRequests to improve the udp proxy.

Really appreciate for your work, vnet is a great project, we will do more works on the network simulate and file more PullRequests as much as we can.

Thanks a lot 😄

**Pull request closed without merging**
