### PR TITLE
Make read notify use sync.Cond instead of chan

### PR DESCRIPTION
**Pull request by edaniels**
We've hit a few cases where using a channel as a notify mechanism is subject to races when we are running multi consumer multi producer scenarios. A sync.Cond is more suitable for this given we can properly broadcast when read deadlines are hit, which this change supports.

I thought we were there with https://github.com/pion/transport/commit/d55a60c7e26d064668001e1d8196d92e69b16b4e but it then revealed #299 where reads can miss an event which is especially pertinent in the simulcast probing test.

Fixes: #299

### CODE REVIEW

**Comment by edaniels** [comment]
Note: This appears to cause 3 more allocs per test. I'm not sure that truly matters.

**Comment by paulwe** [comment]
the races should be sorted by the recent set of changes. 

this proposal ads significant complexity and overhead with no clear benefit. composing channel reads is a lot easier than juggling multiple synchronization primitives. to use a cond we would have to either make changes to `deadline.Deadline` or bring that feature into `Buffer` so the deadline, write, and close behaviors could share the cond.

**Comment by edaniels** [comment]
> the races should be sorted by the recent set of changes.
> 
> this proposal ads significant complexity and overhead with no clear benefit. composing channel reads is a lot easier than juggling multiple synchronization primitives. to use a cond we would have to either make changes to `deadline.Deadline` or bring that feature into `Buffer` so the deadline, write, and close behaviors could share the cond.

The race that is fixed is one present in #299 where a read is missed. The recent set of changes fixed the closing case (so, all future reads are satisfied). The same critical section https://github.com/pion/transport/blob/master/packetio/buffer.go#L262-L264 still has an issue with concurrent readers. I'll revise this into something simpler hopefully, but it needs to be addressed.

**Comment by paulwe** [comment]
> The same critical section https://github.com/pion/transport/blob/master/packetio/buffer.go#L262-L264 still has an issue with concurrent readers

concurrent reads work as expected now. if there is more than one goroutine waiting in the read loop one makes progress after each write and when the buffer closes they both exit.

**Pull request closed without merging**
