### PR TITLE
Add StrictDeadline option to packetio.Buffer

### PR DESCRIPTION
**Pull request by at-wat**
If StrictDeadline option is set to false (default), Read() may return data even if the deadline is exceeded or context is canceled. It may increases the performance.
Set true to make Buffer behaves more like net.Conn.

This also restore improved test reverted by ac22c334.

Related #116

### CODE REVIEW

**Comment by at-wat** [comment]
@Sean-Der @OrlandoCo  this is what https://github.com/pion/transport/pull/116 suggested. It is unrelated to the context introduction.

**Comment by at-wat** [comment]
@Sean-Der @OrlandoCo please take a look.
In webrtc usage, strict deadline handling is not required. This should improve the performance.

This also restores the update of the test reverted by ac22c334b84c0c73ad1806eaf30606bb15aead46

**Review by Sean-Der — APPROVED** [review]

**Comment by Sean-Der** [comment]
nice! that makes sense to me, better to not leave the perf on the table :)

**Comment by Sean-Der** [comment]
sorry that I missed this in all the tagging/pushing

**Comment by jech** [comment]
What's the performance gain?  It's difficult to judge without seeing benchmarks if the change is useful.

**Comment by jech** [comment]
Can you give a usage scenario where setting this to false would be useful? Also, why is the default false?

**Comment by stv0g** [comment]
Hi @jech,

@at-wat motivated the change in this comment:

> In webrtc usage, strict deadline handling is not required. This should improve the performance.

**Comment by stv0g** [comment]
And sorry for not CCing you. I did not knew that you wrote this code.

If you strongly disagree with this change, I will revert it.

**Comment by jech** [comment]
> @at-wat motivated the change in this comment:
> 
>     In webrtc usage, strict deadline handling is not required. This should
>     improve the performance.

I don't understand how this can possibly improve performance.  The code
used to drop obsolete packets straight away.  The new default keeps the
obsolete packets around, which means we spend extra time sending obsolete
packets.  Furthermore, it causes extra bufferbloat.

Thus, I would intuitively expect it to decrease performance.

@at-wat, could you please provide benchmarks that show that this change
improves performance?

**Comment by jech** [comment]
> If you strongly disagree with this change, I will revert it.

I think it should be reverted.  At the very least, the default should be
the opposite of what it is now.

**Comment by stv0g** [comment]
Agreed. I will revert the change.

@at-wat Please feel free to reopen if we have some benchmarks :)

**Pull request merged**
